/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;


@RestController("/")
public class SecurityController {

	   @GetMapping
	    public String helloGradle() {
	        return "Hello GlobalLogic!";
	    }

}
