/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.globallogic.evaluacion.controller;

import java.net.URI;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.globallogic.evaluacion.model.User;
import com.globallogic.evaluacion.service.LoginService;


@RestController("/")
public class SecurityController {
	
	@Autowired LoginService loginSvc;

	@GetMapping("/")
	public String hello() {
		return "Hello GlobalLogic!";
	}   
	
	   
	@PostMapping("/sign-up")
	public ResponseEntity<User> signUp(@RequestBody User newUser) {
		URI uri = null;
		List<String> errors = loginSvc.validateSignUp(newUser);
		
		if(errors == null || errors.size() == 0) {
			loginSvc.saveNewUser(newUser);
			
		}
	   
		return ResponseEntity.created(uri).body(newUser);
	}


	@GetMapping("/login")
	public ResponseEntity<User> login(@RequestParam String token) {
		URI uri = null;
		User user = loginSvc.readUserByToken(token);
		
		return ResponseEntity.created(uri).body(user);
	}   

}
