/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.globallogic.evaluacion.controller;

import java.net.URI;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.globallogic.evaluacion.model.User;
import com.globallogic.evaluacion.service.LoginService;


@RestController("/")
public class SecurityController {
	
	@Autowired LoginService loginSvc;

	@GetMapping("/")
	public String hello() {
		return "Hello GlobalLogic!";
	}   
	
	   
	@PostMapping("/sign-up")
	public ResponseEntity<User> signUp(@RequestBody User newUser) {
		User existUser = null;
		URI uri = null;
	   
		return ResponseEntity.created(uri).body(existUser);
	}

}
